/**
 * Maritime intelligence lookups — vessel type details, flag resolution, MMSI → country.
 */

// ── AIS vessel type → detailed info ──────────────────────────────────────────
export const VESSEL_TYPE_INFO: Record<number, { name: string; emoji: string; category: 'military' | 'cargo' | 'tanker' | 'passenger' | 'fishing' | 'service' | 'other' }> = {
  0:  { name: 'Unknown', emoji: '❓', category: 'other' },
  20: { name: 'Wing in Ground', emoji: '🛩️', category: 'other' },
  30: { name: 'Fishing', emoji: '🎣', category: 'fishing' },
  31: { name: 'Towing', emoji: '⚓', category: 'service' },
  32: { name: 'Towing (Large)', emoji: '⚓', category: 'service' },
  33: { name: 'Dredging', emoji: '🏗️', category: 'service' },
  34: { name: 'Diving Operations', emoji: '🤿', category: 'service' },
  35: { name: 'Military', emoji: '⚔️', category: 'military' },
  36: { name: 'Sailing', emoji: '⛵', category: 'other' },
  37: { name: 'Pleasure Craft', emoji: '🛥️', category: 'other' },
  40: { name: 'High Speed Craft', emoji: '⚡', category: 'passenger' },
  41: { name: 'High Speed Craft (Hazmat A)', emoji: '⚡', category: 'other' },
  42: { name: 'High Speed Craft (Hazmat B)', emoji: '⚡', category: 'other' },
  50: { name: 'Pilot Vessel', emoji: '✈️', category: 'service' },
  51: { name: 'Search & Rescue', emoji: '🆘', category: 'service' },
  52: { name: 'Tug', emoji: '⚓', category: 'service' },
  53: { name: 'Port Tender', emoji: '🚢', category: 'service' },
  54: { name: 'Anti-Pollution', emoji: '🌊', category: 'service' },
  55: { name: 'Law Enforcement', emoji: '🚔', category: 'military' },
  56: { name: 'Local Vessel', emoji: '🚢', category: 'service' },
  57: { name: 'Medical Transport', emoji: '🏥', category: 'service' },
  58: { name: 'Non-Combatant Ship', emoji: '🏥', category: 'military' },
  60: { name: 'Passenger', emoji: '🚢', category: 'passenger' },
  61: { name: 'Passenger (Hazmat A)', emoji: '🚢', category: 'passenger' },
  62: { name: 'Passenger (Hazmat B)', emoji: '🚢', category: 'passenger' },
  63: { name: 'Passenger (Hazmat C)', emoji: '🚢', category: 'passenger' },
  64: { name: 'Passenger (Hazmat D)', emoji: '🚢', category: 'passenger' },
  69: { name: 'Passenger (No Info)', emoji: '🚢', category: 'passenger' },
  70: { name: 'Cargo', emoji: '📦', category: 'cargo' },
  71: { name: 'Cargo (Hazmat A)', emoji: '📦', category: 'cargo' },
  72: { name: 'Cargo (Hazmat B)', emoji: '📦', category: 'cargo' },
  73: { name: 'Cargo (Hazmat C)', emoji: '📦', category: 'cargo' },
  74: { name: 'Cargo (Hazmat D)', emoji: '📦', category: 'cargo' },
  79: { name: 'Cargo (No Info)', emoji: '📦', category: 'cargo' },
  80: { name: 'Tanker', emoji: '🛢️', category: 'tanker' },
  81: { name: 'Tanker (Hazmat A)', emoji: '🛢️', category: 'tanker' },
  82: { name: 'Tanker (Hazmat B)', emoji: '🛢️', category: 'tanker' },
  83: { name: 'Tanker (Hazmat C)', emoji: '🛢️', category: 'tanker' },
  84: { name: 'Tanker (Hazmat D)', emoji: '🛢️', category: 'tanker' },
  89: { name: 'Tanker (No Info)', emoji: '🛢️', category: 'tanker' },
  90: { name: 'Other', emoji: '🚢', category: 'other' },
};

/**
 * Get detailed vessel type info from AIS type code.
 * Handles range types (70-79 = Cargo, 80-89 = Tanker, 60-69 = Passenger).
 */
export function getVesselTypeInfo(typeCode: number | undefined | null): { name: string; emoji: string; category: string } {
  if (typeCode == null) return { name: 'Unknown', emoji: '❓', category: 'other' };
  if (VESSEL_TYPE_INFO[typeCode]) return VESSEL_TYPE_INFO[typeCode];
  // Range fallback
  if (typeCode >= 70 && typeCode < 80) return VESSEL_TYPE_INFO[70];
  if (typeCode >= 80 && typeCode < 90) return VESSEL_TYPE_INFO[80];
  if (typeCode >= 60 && typeCode < 70) return VESSEL_TYPE_INFO[60];
  if (typeCode >= 40 && typeCode < 50) return VESSEL_TYPE_INFO[40];
  return { name: `Type ${typeCode}`, emoji: '🚢', category: 'other' };
}

// ── MMSI prefix → country (MID = Maritime Identification Digits) ─────────────
const MMSI_COUNTRY: Record<string, { code: string; name: string }> = {
  '201': { code: 'AL', name: 'Albania' },
  '202': { code: 'AD', name: 'Andorra' },
  '203': { code: 'AT', name: 'Austria' },
  '204': { code: 'PT', name: 'Azores' },
  '205': { code: 'BE', name: 'Belgium' },
  '206': { code: 'BY', name: 'Belarus' },
  '207': { code: 'BG', name: 'Bulgaria' },
  '209': { code: 'CY', name: 'Cyprus' },
  '210': { code: 'CY', name: 'Cyprus' },
  '211': { code: 'DE', name: 'Germany' },
  '212': { code: 'CY', name: 'Cyprus' },
  '213': { code: 'GE', name: 'Georgia' },
  '214': { code: 'MD', name: 'Moldova' },
  '215': { code: 'MT', name: 'Malta' },
  '218': { code: 'DE', name: 'Germany' },
  '219': { code: 'DK', name: 'Denmark' },
  '220': { code: 'DK', name: 'Denmark' },
  '224': { code: 'ES', name: 'Spain' },
  '225': { code: 'ES', name: 'Spain' },
  '226': { code: 'FR', name: 'France' },
  '227': { code: 'FR', name: 'France' },
  '228': { code: 'FR', name: 'France' },
  '229': { code: 'MT', name: 'Malta' },
  '230': { code: 'FI', name: 'Finland' },
  '231': { code: 'FO', name: 'Faroe Islands' },
  '232': { code: 'GB', name: 'United Kingdom' },
  '233': { code: 'GB', name: 'United Kingdom' },
  '234': { code: 'GB', name: 'United Kingdom' },
  '235': { code: 'GB', name: 'United Kingdom' },
  '236': { code: 'GI', name: 'Gibraltar' },
  '237': { code: 'GR', name: 'Greece' },
  '238': { code: 'HR', name: 'Croatia' },
  '239': { code: 'GR', name: 'Greece' },
  '240': { code: 'GR', name: 'Greece' },
  '241': { code: 'GR', name: 'Greece' },
  '242': { code: 'MA', name: 'Morocco' },
  '243': { code: 'HU', name: 'Hungary' },
  '244': { code: 'NL', name: 'Netherlands' },
  '245': { code: 'NL', name: 'Netherlands' },
  '246': { code: 'NL', name: 'Netherlands' },
  '247': { code: 'IT', name: 'Italy' },
  '248': { code: 'MT', name: 'Malta' },
  '249': { code: 'MT', name: 'Malta' },
  '250': { code: 'IE', name: 'Ireland' },
  '251': { code: 'IS', name: 'Iceland' },
  '255': { code: 'PT', name: 'Madeira' },
  '256': { code: 'MT', name: 'Malta' },
  '257': { code: 'NO', name: 'Norway' },
  '258': { code: 'NO', name: 'Norway' },
  '259': { code: 'NO', name: 'Norway' },
  '261': { code: 'PL', name: 'Poland' },
  '263': { code: 'PT', name: 'Portugal' },
  '265': { code: 'SE', name: 'Sweden' },
  '266': { code: 'SE', name: 'Sweden' },
  '269': { code: 'CH', name: 'Switzerland' },
  '270': { code: 'CZ', name: 'Czechia' },
  '271': { code: 'TR', name: 'Turkey' },
  '272': { code: 'UA', name: 'Ukraine' },
  '273': { code: 'RU', name: 'Russia' },
  '274': { code: 'MK', name: 'North Macedonia' },
  '275': { code: 'LV', name: 'Latvia' },
  '276': { code: 'EE', name: 'Estonia' },
  '277': { code: 'LT', name: 'Lithuania' },
  '278': { code: 'SI', name: 'Slovenia' },
  '279': { code: 'RS', name: 'Serbia' },
  '301': { code: 'AI', name: 'Anguilla' },
  '303': { code: 'US', name: 'Alaska (US)' },
  '304': { code: 'AG', name: 'Antigua & Barbuda' },
  '305': { code: 'AG', name: 'Antigua & Barbuda' },
  '306': { code: 'CW', name: 'Curaçao' },
  '307': { code: 'AW', name: 'Aruba' },
  '308': { code: 'BS', name: 'Bahamas' },
  '309': { code: 'BS', name: 'Bahamas' },
  '310': { code: 'BM', name: 'Bermuda' },
  '311': { code: 'BS', name: 'Bahamas' },
  '312': { code: 'BZ', name: 'Belize' },
  '314': { code: 'BB', name: 'Barbados' },
  '316': { code: 'CA', name: 'Canada' },
  '319': { code: 'KY', name: 'Cayman Islands' },
  '321': { code: 'CR', name: 'Costa Rica' },
  '323': { code: 'CU', name: 'Cuba' },
  '325': { code: 'DM', name: 'Dominica' },
  '327': { code: 'DO', name: 'Dominican Republic' },
  '329': { code: 'GP', name: 'Guadeloupe' },
  '330': { code: 'GD', name: 'Grenada' },
  '332': { code: 'GT', name: 'Guatemala' },
  '334': { code: 'HN', name: 'Honduras' },
  '336': { code: 'HT', name: 'Haiti' },
  '338': { code: 'US', name: 'United States' },
  '339': { code: 'JM', name: 'Jamaica' },
  '341': { code: 'KN', name: 'Saint Kitts & Nevis' },
  '343': { code: 'LC', name: 'Saint Lucia' },
  '345': { code: 'MX', name: 'Mexico' },
  '347': { code: 'MQ', name: 'Martinique' },
  '348': { code: 'MS', name: 'Montserrat' },
  '350': { code: 'NI', name: 'Nicaragua' },
  '351': { code: 'PA', name: 'Panama' },
  '352': { code: 'PA', name: 'Panama' },
  '353': { code: 'PA', name: 'Panama' },
  '354': { code: 'PA', name: 'Panama' },
  '355': { code: 'PA', name: 'Panama' },
  '356': { code: 'PA', name: 'Panama' },
  '357': { code: 'PA', name: 'Panama' },
  '358': { code: 'PR', name: 'Puerto Rico' },
  '361': { code: 'PM', name: 'Saint Pierre' },
  '362': { code: 'TT', name: 'Trinidad & Tobago' },
  '364': { code: 'TC', name: 'Turks & Caicos' },
  '366': { code: 'US', name: 'United States' },
  '367': { code: 'US', name: 'United States' },
  '368': { code: 'US', name: 'United States' },
  '369': { code: 'US', name: 'United States' },
  '370': { code: 'PA', name: 'Panama' },
  '371': { code: 'PA', name: 'Panama' },
  '372': { code: 'PA', name: 'Panama' },
  '373': { code: 'PA', name: 'Panama' },
  '374': { code: 'PA', name: 'Panama' },
  '375': { code: 'VC', name: 'Saint Vincent' },
  '376': { code: 'VC', name: 'Saint Vincent' },
  '377': { code: 'VC', name: 'Saint Vincent' },
  '378': { code: 'VG', name: 'British Virgin Islands' },
  '379': { code: 'VI', name: 'US Virgin Islands' },
  '401': { code: 'AF', name: 'Afghanistan' },
  '403': { code: 'SA', name: 'Saudi Arabia' },
  '405': { code: 'BD', name: 'Bangladesh' },
  '408': { code: 'BH', name: 'Bahrain' },
  '410': { code: 'BT', name: 'Bhutan' },
  '412': { code: 'CN', name: 'China' },
  '413': { code: 'CN', name: 'China' },
  '414': { code: 'CN', name: 'China' },
  '416': { code: 'TW', name: 'Taiwan' },
  '417': { code: 'LK', name: 'Sri Lanka' },
  '419': { code: 'IN', name: 'India' },
  '422': { code: 'IR', name: 'Iran' },
  '423': { code: 'AZ', name: 'Azerbaijan' },
  '425': { code: 'IQ', name: 'Iraq' },
  '428': { code: 'IL', name: 'Israel' },
  '431': { code: 'JP', name: 'Japan' },
  '432': { code: 'JP', name: 'Japan' },
  '434': { code: 'TM', name: 'Turkmenistan' },
  '436': { code: 'KZ', name: 'Kazakhstan' },
  '438': { code: 'JO', name: 'Jordan' },
  '440': { code: 'KR', name: 'South Korea' },
  '441': { code: 'KR', name: 'South Korea' },
  '443': { code: 'PS', name: 'Palestine' },
  '445': { code: 'KP', name: 'North Korea' },
  '447': { code: 'KW', name: 'Kuwait' },
  '450': { code: 'LB', name: 'Lebanon' },
  '455': { code: 'MV', name: 'Maldives' },
  '457': { code: 'MN', name: 'Mongolia' },
  '459': { code: 'NP', name: 'Nepal' },
  '461': { code: 'OM', name: 'Oman' },
  '463': { code: 'PK', name: 'Pakistan' },
  '466': { code: 'QA', name: 'Qatar' },
  '468': { code: 'SY', name: 'Syria' },
  '470': { code: 'AE', name: 'UAE' },
  '472': { code: 'TJ', name: 'Tajikistan' },
  '473': { code: 'YE', name: 'Yemen' },
  '475': { code: 'SG', name: 'Singapore' },
  '477': { code: 'HK', name: 'Hong Kong' },
  '478': { code: 'BA', name: 'Bosnia' },
  '501': { code: 'FR', name: 'Adelie Land (FR)' },
  '503': { code: 'AU', name: 'Australia' },
  '506': { code: 'MM', name: 'Myanmar' },
  '508': { code: 'BN', name: 'Brunei' },
  '510': { code: 'FM', name: 'Micronesia' },
  '511': { code: 'PW', name: 'Palau' },
  '512': { code: 'NZ', name: 'New Zealand' },
  '514': { code: 'KH', name: 'Cambodia' },
  '515': { code: 'KH', name: 'Cambodia' },
  '516': { code: 'CX', name: 'Christmas Island' },
  '518': { code: 'CK', name: 'Cook Islands' },
  '520': { code: 'FJ', name: 'Fiji' },
  '525': { code: 'ID', name: 'Indonesia' },
  '529': { code: 'KI', name: 'Kiribati' },
  '531': { code: 'LA', name: 'Laos' },
  '533': { code: 'MY', name: 'Malaysia' },
  '536': { code: 'MP', name: 'N. Mariana Islands' },
  '538': { code: 'MH', name: 'Marshall Islands' },
  '540': { code: 'NC', name: 'New Caledonia' },
  '542': { code: 'NU', name: 'Niue' },
  '544': { code: 'NR', name: 'Nauru' },
  '546': { code: 'PF', name: 'French Polynesia' },
  '548': { code: 'PH', name: 'Philippines' },
  '553': { code: 'PG', name: 'Papua New Guinea' },
  '555': { code: 'PN', name: 'Pitcairn' },
  '557': { code: 'SB', name: 'Solomon Islands' },
  '559': { code: 'AS', name: 'American Samoa' },
  '561': { code: 'WS', name: 'Samoa' },
  '563': { code: 'TH', name: 'Thailand' },
  '564': { code: 'TH', name: 'Thailand' },
  '565': { code: 'TO', name: 'Tonga' },
  '566': { code: 'TL', name: 'Timor-Leste' },
  '567': { code: 'TV', name: 'Tuvalu' },
  '570': { code: 'VN', name: 'Vietnam' },
  '572': { code: 'VU', name: 'Vanuatu' },
  '574': { code: 'VN', name: 'Vietnam' },
  '576': { code: 'WF', name: 'Wallis & Futuna' },
  '601': { code: 'ZA', name: 'South Africa' },
  '603': { code: 'AO', name: 'Angola' },
  '605': { code: 'DZ', name: 'Algeria' },
  '607': { code: 'FR', name: 'Saint Paul (FR)' },
  '608': { code: 'IO', name: 'Ascension Island' },
  '609': { code: 'BI', name: 'Burundi' },
  '610': { code: 'BJ', name: 'Benin' },
  '611': { code: 'BW', name: 'Botswana' },
  '612': { code: 'CF', name: 'Central African Rep.' },
  '613': { code: 'CM', name: 'Cameroon' },
  '615': { code: 'CG', name: 'Congo' },
  '616': { code: 'KM', name: 'Comoros' },
  '617': { code: 'CV', name: 'Cabo Verde' },
  '618': { code: 'FR', name: 'Crozet (FR)' },
  '619': { code: 'CI', name: "Côte d'Ivoire" },
  '620': { code: 'KM', name: 'Comoros' },
  '621': { code: 'DJ', name: 'Djibouti' },
  '622': { code: 'EG', name: 'Egypt' },
  '624': { code: 'ET', name: 'Ethiopia' },
  '625': { code: 'ER', name: 'Eritrea' },
  '626': { code: 'GA', name: 'Gabon' },
  '627': { code: 'GH', name: 'Ghana' },
  '629': { code: 'GM', name: 'Gambia' },
  '630': { code: 'GW', name: 'Guinea-Bissau' },
  '631': { code: 'GQ', name: 'Equatorial Guinea' },
  '632': { code: 'GN', name: 'Guinea' },
  '633': { code: 'BF', name: 'Burkina Faso' },
  '634': { code: 'KE', name: 'Kenya' },
  '635': { code: 'FR', name: 'Kerguelen (FR)' },
  '636': { code: 'LR', name: 'Liberia' },
  '637': { code: 'LR', name: 'Liberia' },
  '642': { code: 'LY', name: 'Libya' },
  '644': { code: 'LS', name: 'Lesotho' },
  '645': { code: 'MU', name: 'Mauritius' },
  '647': { code: 'MG', name: 'Madagascar' },
  '649': { code: 'ML', name: 'Mali' },
  '650': { code: 'MZ', name: 'Mozambique' },
  '654': { code: 'MR', name: 'Mauritania' },
  '655': { code: 'MW', name: 'Malawi' },
  '656': { code: 'NE', name: 'Niger' },
  '657': { code: 'NG', name: 'Nigeria' },
  '659': { code: 'NA', name: 'Namibia' },
  '660': { code: 'RE', name: 'Réunion' },
  '661': { code: 'RW', name: 'Rwanda' },
  '662': { code: 'SD', name: 'Sudan' },
  '663': { code: 'SN', name: 'Senegal' },
  '664': { code: 'SC', name: 'Seychelles' },
  '665': { code: 'SH', name: 'Saint Helena' },
  '666': { code: 'SO', name: 'Somalia' },
  '667': { code: 'SL', name: 'Sierra Leone' },
  '668': { code: 'ST', name: 'São Tomé' },
  '669': { code: 'SZ', name: 'Eswatini' },
  '670': { code: 'TD', name: 'Chad' },
  '671': { code: 'TG', name: 'Togo' },
  '672': { code: 'TN', name: 'Tunisia' },
  '674': { code: 'TZ', name: 'Tanzania' },
  '675': { code: 'UG', name: 'Uganda' },
  '676': { code: 'CD', name: 'DR Congo' },
  '677': { code: 'TZ', name: 'Tanzania' },
  '678': { code: 'ZM', name: 'Zambia' },
  '679': { code: 'ZW', name: 'Zimbabwe' },
  '701': { code: 'AR', name: 'Argentina' },
  '710': { code: 'BR', name: 'Brazil' },
  '720': { code: 'BO', name: 'Bolivia' },
  '725': { code: 'CL', name: 'Chile' },
  '730': { code: 'CO', name: 'Colombia' },
  '735': { code: 'EC', name: 'Ecuador' },
  '740': { code: 'FK', name: 'Falkland Islands' },
  '745': { code: 'GF', name: 'French Guiana' },
  '750': { code: 'GY', name: 'Guyana' },
  '755': { code: 'PY', name: 'Paraguay' },
  '760': { code: 'PE', name: 'Peru' },
  '765': { code: 'SR', name: 'Suriname' },
  '770': { code: 'UY', name: 'Uruguay' },
  '775': { code: 'VE', name: 'Venezuela' },
};

/**
 * Get country from MMSI Maritime Identification Digits (first 3 digits).
 */
export function getCountryFromMMSI(mmsi: string): { code: string; name: string } | null {
  if (!mmsi || mmsi.length < 3) return null;
  const mid = mmsi.slice(0, 3);
  return MMSI_COUNTRY[mid] || null;
}

/**
 * ISO country code → flag emoji.
 */
export function countryFlag(code: string): string {
  if (!code || code.length < 2) return '';
  const c = code.toUpperCase();
  return String.fromCodePoint(
    0x1F1E6 + c.charCodeAt(0) - 65,
    0x1F1E6 + c.charCodeAt(1) - 65,
  );
}

/**
 * Get category color for vessel type.
 */
export function getVesselCategoryColor(category: string): string {
  switch (category) {
    case 'military': return '#ef4444';
    case 'cargo': return '#3b82f6';
    case 'tanker': return '#f97316';
    case 'passenger': return '#22d3ee';
    case 'fishing': return '#10b981';
    case 'service': return '#8b5cf6';
    default: return '#64748b';
  }
}
